### PR TITLE
Add Dockerfile

### LINKED ISSUE #11: Create Dockerfile for this repo

### PR DESCRIPTION
**Pull request by northwestwitch**
fix #11

### This PR adds | fixes:
- Adds a Dockerfile to the app

**How to prepare for test**:
- [ ] Checkout to this branch

### How to test:
- [x] Build the container --> `docker build -t chanjo-report:latest .`
- [x] Run the container --> `docker run --name chanjo-report chanjo-report`

### Expected outcome:
- [x] The commands above should work

### Review:
- [ ] Code approved by
- [x] Tests executed by CR
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Works!

image

**Comment by moonso** [comment]
Great @northwestwitch !
Two things:

1. Should it not be just `docker run --rm chanjo-report` and it will send the argument as specified in file?
1. Could we try to create a docker-compose.yml where we create a chanjo database and populates it with some data. Then the usage of this could be fully tested on it's own

**Comment by northwestwitch** [comment]
> Great @northwestwitch !
> Two things:
> 
> 1. Should it not be just `docker run --rm chanjo-report` and it will send the argument as specified in file?

Sure, you can run it also with the --rm tag:

image

> 2. Could we try to create a docker-compose.yml where we create a chanjo database and populates it with some data. Then the usage of this could be fully tested on it's own

I'd rather do it in another PR, because it will take me time to setup a demo database container connected to chanjo container and chanjo-report container

**Comment by northwestwitch** [comment]
> > Great @northwestwitch !
> > Two things:
> > 
> > 1. Should it not be just `docker run --rm chanjo-report` and it will send the argument as specified in file?
> 
> Sure, you can run it also with the --rm tag:
> 
> image
> 
> > 1. Could we try to create a docker-compose.yml where we create a chanjo database and populates it with some data. Then the usage of this could be fully tested on it's own
> 
> I'd rather do it in another PR, because it will take me time to figure out how to set up a demo database container connected to chanjo container, run chanjo to populate the databse and then create a report with this container

And there is also the fact that if we merge this and we push the image to Docker Hub, then the docker-compose could pull this image directly from there, instead of having to build this one first

**Comment by northwestwitch** [comment]
> > > Great @northwestwitch !
> > > Two things:
> > > 
> > > 1. Should it not be just `docker run --rm chanjo-report` and it will send the argument as specified in file?
> > 
> > 
> > Sure, you can run it also with the --rm tag:
> > image
> > > 1. Could we try to create a docker-compose.yml where we create a chanjo database and populates it with some data. Then the usage of this could be fully tested on it's own
> > 
> > 
> > I'd rather do it in another PR, because it will take me time to figure out how to set up a demo database container connected to chanjo container, run chanjo to populate the databse and then create a report with this container
> 
> And there is also the fact that if we merge this and we push the image to Docker Hub, then the docker-compose could pull this image directly from there, instead of having to build it from the branch

**Review by moonso — APPROVED** [review]
Nice 🍶

**Pull request merged**
