### PR TITLE
Dockerfile with virtual env and multi-stage buiid

### LINKED ISSUE #33: Fix Dockefile to execute commands from virtual env as non-root user
When you use the Docker image: you get the hint: `WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv `

### PR DESCRIPTION
**Pull request by northwestwitch**
Modified Dockerfile to:
- Execute the app from a virtual environment (fix #33)
- Build Dockerfile with multi-stage build

## Test1 --> venv
Make sure the Dockefile works. Run:
- make setup
- make report
- Go to report: http://localhost:5000/report?sample_id=sample1&sample_id=sample2&sample_id=sample3

## Test2 --> multi-stage build
- Build Dockerfile from master branch and build Dockerfile from this branch. The one from this branch should be built faster

### CODE REVIEW

**Comment by northwestwitch** [comment]
Test docker-compose (make commands): 🆗 

image

**Comment by northwestwitch** [comment]
@dnil an easy review for when you have some time. No rush!

**Comment by dnil** [comment]
Yep, code looks good and runs just fine on a local docker:
Screenshot 2022-04-29 at 11 47 49

**Review by dnil — APPROVED** [review]
👍

**Comment by northwestwitch** [comment]
Thanks for the review!

**Pull request merged**
